apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name }}
  labels:
    app: {{ .Chart.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ .Release.name }}
