name: On merge test
on:
  workflow_dispatch:
  #push:
  pull_request:
      branches: [ main ]
## breaking change test
jobs:
  on-push-ci:
    runs-on: ubuntu-latest

# permissions required by configure AWS creds step
    permissions:
      id-token: write
      contents: write
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
    
#       - name: Checkout
#         run: echo "say hello"

      - name: test failing
        run: |
          TEST1=$(cat CI-helper.py | grep test22)
          echo $TEST1
          #if [[ $TEST == '#test22' ]]; 
          #then 
           # echo 'hello'; 
          #fi
